### ISSUE TITLE
Доработки

### ISSUE THREAD

**Issue by alexkoss** [emeraldbird/cassandra-docker-compose#1]
Добрый день, Никита. Меня зовут Александр, представитель БалтИнфоКом.

Ваше решение не удовлетворяет поставленному заданию.

Нужно добавить команды (и их вывод), необходимые для подключения с нехоста к контейнеру по ip из локальной сети через cqlsh

**Comment by alexkoss** [comment]
@emeraldbird Добрый день, Никита, будете доделывать тестовое?

**Comment by emeraldbird** [comment]
@alexkoss Александр, добрый день! Прошу прощения за такую задержку с ответом, был занят защитой диплома. Меня заинтересовал другой оффер, поэтому, вероятно, это уже не очень актуально. Благодарю за уделенное мне время и удачи в поисках кандидата!
